"use client";
import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import*as React from"react";import{useEffect,useRef,useState}from"react";import{addPropertyControls,ControlType}from"framer";import{liquidMetalFragmentShader,ShaderMount}from"@paper-design/shaders";/* ------------------------------------------------------------
   Inline SVG renderer with color override
------------------------------------------------------------ */function InlineSVG({src,size,color}){const[svg,setSvg]=useState(null);useEffect(()=>{if(!src){setSvg(null);return;}fetch(src).then(res=>res.text()).then(text=>{const normalized=text.replace(/stroke="(?!none).*?"/g,'stroke="currentColor"').replace(/fill="(?!none).*?"/g,'fill="currentColor"');setSvg(normalized);});},[src]);if(!svg)return null;return /*#__PURE__*/_jsx("div",{style:{width:size,height:size,color,display:"flex",alignItems:"center",justifyContent:"center",overflow:"hidden"},dangerouslySetInnerHTML:{__html:svg}});}/* ------------------------------------------------------------
   Main Component
------------------------------------------------------------ */export default function IconWebglShader(props){const{size,strokeWidth,iconSize,innerTop,innerBottom,iconColor,iconSvg}=props;const shaderRef=useRef(null);const maskId=React.useId();const hasCustomIcon=typeof iconSvg==="string"&&iconSvg.trim().length>0;useEffect(()=>{if(!shaderRef.current)return;const mount=new ShaderMount(shaderRef.current,liquidMetalFragmentShader,{// 🔒 Locked shader uniforms (stable & zoom-safe)
u_repetition:1.6,u_softness:.45,u_scale:1.6,u_angle:120,u_shiftRed:.35,u_shiftBlue:.35,u_distortion:0,u_contour:0,u_shape:1,u_offsetX:.1,u_offsetY:-.1},undefined,1);return()=>mount?.destroy?.();},[]);const radius=size/2;const ringRadius=radius-strokeWidth/2;return /*#__PURE__*/_jsxs("div",{style:{width:size,height:size,position:"relative",display:"inline-block"},children:[/*#__PURE__*/_jsx("svg",{width:size,height:size,style:{position:"absolute",inset:0},children:/*#__PURE__*/_jsx("defs",{children:/*#__PURE__*/_jsxs("mask",{id:maskId,children:[/*#__PURE__*/_jsx("rect",{width:"100%",height:"100%",fill:"black"}),/*#__PURE__*/_jsx("circle",{cx:radius,cy:radius,r:ringRadius,fill:"none",stroke:"white",strokeWidth:strokeWidth})]})})}),/*#__PURE__*/_jsx("div",{ref:shaderRef,style:{position:"absolute",inset:0,borderRadius:"50%",filter:"contrast(1.4) brightness(1.2)",WebkitMask:`url(#${maskId})`,mask:`url(#${maskId})`}}),/*#__PURE__*/_jsx("div",{style:{position:"absolute",inset:strokeWidth,borderRadius:"50%",background:`linear-gradient(180deg, ${innerTop}, ${innerBottom})`,boxShadow:"inset 0 1px 4px rgba(255,255,255,0.1), inset 0 -6px 12px rgba(0,0,0,0.6)",zIndex:1}}),/*#__PURE__*/_jsx("div",{style:{position:"absolute",top:"50%",left:"50%",transform:"translate(-50%, -50%)",width:iconSize,height:iconSize,display:"flex",alignItems:"center",justifyContent:"center",color:iconColor,zIndex:2,pointerEvents:"none"},children:hasCustomIcon?/*#__PURE__*/_jsx(InlineSVG,{src:iconSvg,size:iconSize,color:iconColor}):/*#__PURE__*/_jsxs("svg",{viewBox:"0 0 1024 1024",width:"100%",height:"100%",fill:"currentColor",style:{transform:"rotate(-45deg)"},children:[/*#__PURE__*/_jsx("path",{d:"M843.968 896a51.072 51.072 0 0 1-51.968-52.032V232H180.032A51.072 51.072 0 0 1 128 180.032c0-29.44 22.528-52.032 52.032-52.032h663.936c29.44 0 52.032 22.528 52.032 52.032v663.936c0 29.44-22.528 52.032-52.032 52.032z"}),/*#__PURE__*/_jsx("path",{d:"M180.032 896a49.92 49.92 0 0 1-36.48-15.616c-20.736-20.8-20.736-53.76 0-72.832L807.616 143.616c20.864-20.8 53.76-20.8 72.832 0 20.8 20.8 20.8 53.76 0 72.768L216.384 880.384a47.232 47.232 0 0 1-36.352 15.616z"})]})})]});}/* ------------------------------------------------------------
   Framer Controls
------------------------------------------------------------ */addPropertyControls(IconWebglShader,{size:{type:ControlType.Number,defaultValue:220},strokeWidth:{type:ControlType.Number,defaultValue:3},iconSize:{type:ControlType.Number,defaultValue:72},iconSvg:{type:ControlType.File,title:"Icon SVG",allowedFileTypes:["svg"],description:"Upload a single-color SVG icon"},iconColor:{type:ControlType.Color,defaultValue:"#8a8a8a"},innerTop:{type:ControlType.Color,defaultValue:"#1c1c1c"},innerBottom:{type:ControlType.Color,defaultValue:"#000000"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"IconWebglShader","slots":[],"annotations":{"framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./IconWebglShader.map