"use client";
import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{addPropertyControls,ControlType,RenderTarget,useIsStaticRenderer}from"framer";import{startTransition,useEffect,useId,useMemo,useState}from"react";/**
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerIntrinsicWidth 28
 * @framerIntrinsicHeight 6
 */export default function SearchingDots(props){if(props.show===false||props.count===0||props.visible===false)return null;const{count=3,dotSize=6,gap=5,color="rgb(251, 252, 254)",dimOpacity=.15,cycleDuration=1.4,stagger=.18,animate=true}=props;const safeCountValue=Number.isFinite(count)?count:3;const safeDotSize=Number.isFinite(dotSize)?dotSize:6;const safeGap=Number.isFinite(gap)?gap:5;const safeColor=typeof color==="string"?color:"rgb(251, 252, 254)";const safeDimOpacity=Number.isFinite(dimOpacity)?dimOpacity:.15;const safeCycleDuration=Number.isFinite(cycleDuration)?cycleDuration:1.4;const safeStagger=Number.isFinite(stagger)?stagger:.18;const safeAnimate=typeof animate==="boolean"?animate:true;const reactId=useId();const safeId=useMemo(()=>reactId.replace(/[:]/g,""),[reactId]);const animationName=`searchingDotsPulse_${safeId}`;const isStaticRenderer=useIsStaticRenderer();const isCanvasRenderTarget=useMemo(()=>{return RenderTarget.current()===RenderTarget.canvas;},[]);const safeCount=Math.max(1,Math.min(6,Math.round(safeCountValue)));const canAnimate=safeAnimate&&safeCycleDuration>0&&!isStaticRenderer&&!isCanvasRenderTarget;const[prefersReducedMotion,setPrefersReducedMotion]=useState(()=>{if(typeof window==="undefined"||typeof window.matchMedia!=="function")return false;return window.matchMedia("(prefers-reduced-motion: reduce)").matches;});useEffect(()=>{if(typeof window==="undefined"||typeof window.matchMedia!=="function")return;const mediaQuery=window.matchMedia("(prefers-reduced-motion: reduce)");const handleChange=()=>{startTransition(()=>{setPrefersReducedMotion(mediaQuery.matches);});};handleChange();if(typeof mediaQuery.addEventListener==="function"){mediaQuery.addEventListener("change",handleChange);return()=>mediaQuery.removeEventListener("change",handleChange);}mediaQuery.addListener(handleChange);return()=>mediaQuery.removeListener(handleChange);},[]);const baseDelay=useMemo(()=>{if(typeof window==="undefined"||typeof performance==="undefined"||safeCycleDuration<=0){return 0;}return-(performance.now()/1e3%safeCycleDuration);},[safeCycleDuration]);const dots=useMemo(()=>{return Array.from({length:safeCount},(_,index)=>index);},[safeCount]);return /*#__PURE__*/_jsxs("div",{"aria-hidden":"true",style:{position:"relative",width:"100%",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",pointerEvents:"none"},children:[/*#__PURE__*/_jsx("style",{children:`
                @keyframes ${animationName} {
                    0% { opacity: 1; }
                    8% { opacity: 1; }
                    26% { opacity: ${safeDimOpacity}; }
                    46% { opacity: 1; }
                    100% { opacity: 1; }
                }
            `}),/*#__PURE__*/_jsx("div",{style:{position:"relative",display:"flex",alignItems:"center",justifyContent:"center",gap:safeGap},children:dots.map(index=>{const shouldAnimate=canAnimate&&!prefersReducedMotion;const delay=(()=>{if(!shouldAnimate||safeCycleDuration<=0)return 0;const rawDelay=baseDelay+index*safeStagger;return-((-rawDelay%safeCycleDuration+safeCycleDuration)%safeCycleDuration);})();return /*#__PURE__*/_jsx("div",{style:{width:safeDotSize,height:safeDotSize,borderRadius:"999px",background:safeColor,opacity:1,animation:shouldAnimate?`${animationName} ${safeCycleDuration}s cubic-bezier(0.45, 0, 0.55, 1) infinite`:undefined,animationDelay:shouldAnimate?`${delay}s`:undefined}},index);})})]});}addPropertyControls(SearchingDots,{count:{type:ControlType.Number,title:"Count",defaultValue:3,min:1,max:6,step:1},dotSize:{type:ControlType.Number,title:"Dot Size",defaultValue:6,min:1,max:24,step:1,unit:"px"},gap:{type:ControlType.Number,title:"Gap",defaultValue:5,min:0,max:24,step:1,unit:"px"},color:{type:ControlType.Color,title:"Color",defaultValue:"rgb(251, 252, 254)"},dimOpacity:{type:ControlType.Number,title:"Dim Opacity",defaultValue:.15,min:0,max:1,step:.01},cycleDuration:{type:ControlType.Number,title:"Duration",defaultValue:1.4,min:.2,max:8,step:.01,unit:"s"},stagger:{type:ControlType.Number,title:"Stagger",defaultValue:.18,min:0,max:2,step:.01,unit:"s"},animate:{type:ControlType.Boolean,title:"Animate",defaultValue:true,enabledTitle:"On",disabledTitle:"Off",description:"Built by Matthias \xd6lschlegel 💪\n[Explore more components](https://framer.link/fsd2pgh)"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"SearchingDots","slots":[],"annotations":{"framerContractVersion":"1","framerIntrinsicWidth":"28","framerSupportedLayoutHeight":"any-prefer-fixed","framerSupportedLayoutWidth":"any-prefer-fixed","framerIntrinsicHeight":"6"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./SearchingDots.map