"use client";
import{jsx as _jsx}from"react/jsx-runtime";import{addPropertyControls,ControlType,RenderTarget}from"framer";import Cal,{getCalApi}from"@calcom/embed-react";import{useEffect,useMemo,useRef,useState}from"react";var BookerLayouts;var EmbedTheme;/**
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight fixed
 *
 * @framerDisableUnlink
 *
 * @framerIntrinsicHeight 575
 * @framerIntrinsicWidth 1000
 */export default function Calcom(props){const{layout,eventLink,darkTheme,lightTheme,theme,showEventTypeDetails,namespace=""}=props;const apiRef=useRef(null);const isOnCanvas=RenderTarget.current()===RenderTarget.canvas;// Stable namespace (never changes across renders)
const namespaceRef=useRef(namespace||`cal-${Math.random().toString(36).slice(2)}`);const resolvedNamespace=namespaceRef.current;const[embedInfo,setEmbedInfo]=useState({origin:"",username:"",eventTypeSlug:"",teamEventTypeSlug:""});const[embedLoaded,setEmbedLoaded]=useState(false);/**
     * 1) Parse URL & derive embed info
     */useEffect(()=>{let url;try{let normalized=eventLink?.trim()||"";if(!/^https?:\/\//i.test(normalized)){normalized="https://"+normalized;}url=new URL(normalized);}catch(err){console.error(`Incorrect URL: ${eventLink}`,err);return;}const[username,eventTypeSlug="",teamEventTypeSlug=""]=url.pathname.slice(1).split("/");if(!username){console.error("URL must include at least a username.");return;}setEmbedInfo({origin:url.origin,username,eventTypeSlug,teamEventTypeSlug});},[eventLink]);useEffect(()=>{const handleLinkReady=e=>{setEmbedLoaded(true);};(async()=>{if(embedLoaded)return;apiRef.current=await getCalApi({namespace:resolvedNamespace});apiRef.current("on",{action:"linkReady",callback:handleLinkReady});})();return()=>{if(!apiRef.current)return;apiRef.current("off",{action:"linkReady",callback:handleLinkReady});};},[resolvedNamespace,embedLoaded]);useEffect(()=>{(async()=>{if(!embedLoaded||!apiRef.current)return;apiRef.current("ui",{cssVarsPerTheme:{light:{"cal-brand":lightTheme},dark:{"cal-brand":darkTheme}},hideEventTypeDetails:!showEventTypeDetails,layout,theme});})();},[embedLoaded,lightTheme,darkTheme,showEventTypeDetails,layout,theme,resolvedNamespace]);/**
     * Build calLink safely
     */const calLink=useMemo(()=>{if(!embedInfo.username)return"";let link=`${embedInfo.username}/${embedInfo.eventTypeSlug}`;if(embedInfo.teamEventTypeSlug){link+=`/${embedInfo.teamEventTypeSlug}`;}return link;},[embedInfo]);if(!calLink)return null;return /*#__PURE__*/_jsx("div",{style:{position:"relative",width:"100%",height:"100%"},children:[/*#__PURE__*/_jsx("div",{"aria-hidden":embedLoaded,style:{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:12,opacity:embedLoaded?0:1,transition:"opacity .4s ease",pointerEvents:"none"},children:[/*#__PURE__*/_jsx("span",{style:{width:10,height:10,borderRadius:"50%",background:"#17849B",boxShadow:"0 0 0 6px rgba(23,132,155,0.15)",animation:"calcomPulse 1.2s ease-in-out infinite"}}),/*#__PURE__*/_jsx("span",{style:{fontSize:12,fontWeight:600,letterSpacing:"0.04em",color:"#71717a"},children:"Loading scheduler…"})]}),/*#__PURE__*/_jsx("div",{style:{position:"absolute",inset:0,opacity:embedLoaded?1:0,transition:"opacity .5s cubic-bezier(0.16, 1, 0.3, 1)"},children:/*#__PURE__*/_jsx(Cal,{namespace:resolvedNamespace,calLink:calLink,calOrigin:embedInfo.origin,style:isOnCanvas?{height:"100%",overflow:"clip"}:{width:"100%",height:"100%",overflow:"scroll"},config:{layout,theme}},`${eventLink}-${resolvedNamespace}`)}),/*#__PURE__*/_jsx("style",{children:"@keyframes calcomPulse{0%,100%{transform:scale(1);opacity:1}50%{transform:scale(1.4);opacity:.5}}"})]});}addPropertyControls(Calcom,{eventLink:{title:"Event Link",type:ControlType.String,defaultValue:"https://cal.com/framer-placeholder/default"},theme:{type:ControlType.Enum,options:["auto","light","dark"],optionTitles:["Auto","Light","Dark"],defaultValue:"auto"},lightTheme:{type:ControlType.Color,defaultValue:"#292929",title:"Light Color"},darkTheme:{type:ControlType.Color,defaultValue:"#fafafa",title:"Dark Color"},showEventTypeDetails:{type:ControlType.Enum,title:"Event Info",defaultValue:true,displaySegmentedControl:true,segmentedControlDirection:"horizontal",options:[true,false],optionTitles:["Show","Hide"]},layout:{type:ControlType.Enum,options:["month_view","column_view","week_view"],optionTitles:["Month View","Column View","Week View"],defaultValue:"month_view"}});Calcom.displayName="Cal.com";
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"Calcom","slots":[],"annotations":{"framerIntrinsicWidth":"1000","framerSupportedLayoutHeight":"fixed","framerContractVersion":"1","framerDisableUnlink":"*","framerSupportedLayoutWidth":"fixed","framerIntrinsicHeight":"575"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Calcom.map